# src/report/sections/technical_details.py
"""Technical details section: markdown/HTML renderers.

Moved verbatim out of report_generator.py (pure structural split, no logic change).
"""

from datetime import datetime
from typing import Dict, List


def generate_technical_details(data_sources: Dict, model_tag: str) -> List[str]:
    """Generate technical details section."""
    lines = [
        "## 📁 Technical Details",
        "",
        f"- **Model Tag**: {model_tag}",
        f"- **Generated**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "",
        "### Data Sources",
    ]

    # List all data sources used
    for source_name, source_data in data_sources.items():
        if source_name == "plots":
            lines.append(f"- **Plots**: {len(source_data)} chart files")
        elif source_name == "statistical_validation":
            lines.append(
                "- **Statistical Validation**: Bootstrap analysis and out-of-sample testing"
            )
        elif source_name == "baseline_comparison":
            lines.append(
                "- **Baseline Comparison**: Performance vs multiple strategies"
            )
        elif source_name == "parsed_data":
            n_periods = len(source_data) if hasattr(source_data, "__len__") else "N/A"
            lines.append(f"- **Parsed Data**: {n_periods} trading periods")
        else:
            lines.append(f"- **{source_name.replace('_', ' ').title()}**: Available")

    lines.extend(
        [
            "",
            "### Analysis Components",
            "- Statistical significance testing (bootstrap)",
            "- Out-of-sample validation",
            "- Risk-adjusted performance metrics",
            "- Decision calibration analysis",
            "- Baseline strategy comparisons",
            "- Rolling performance analysis",
            "",
            "---",
            "",
            "*This report was automatically generated by the LLM Finance Experiment framework.*",
            "*For questions about methodology or results, refer to the technical documentation.*",
        ]
    )

    return lines


def generate_technical_details_html(data_sources: Dict, model_tag: str) -> str:
    """Generate technical details section in HTML."""
    html = f"""            <div class="section">
                <h2>📁 Technical Details</h2>
                <div class="metric-grid">
                    <div class="metric-card">
                        <div class="label">Model Tag</div>
                        <div class="value">{model_tag}</div>
                    </div>
                    <div class="metric-card">
                        <div class="label">Generated</div>
                        <div class="value">{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</div>
                    </div>
                </div>

                <h3>Data Sources</h3>
                <div class="data-sources">
"""

    # List all data sources used
    for source_name, source_data in data_sources.items():
        if source_name == "plots":
            html += f"""                    <div class="data-source-item">Plots: {len(source_data)} chart files</div>
"""
        elif source_name == "statistical_validation":
            html += """                    <div class="data-source-item">Statistical Validation: Bootstrap analysis and out-of-sample testing</div>
"""
        elif source_name == "baseline_comparison":
            html += """                    <div class="data-source-item">Baseline Comparison: Performance vs multiple strategies</div>
"""
        elif source_name == "parsed_data":
            n_periods = len(source_data) if hasattr(source_data, "__len__") else "N/A"
            html += f"""                    <div class="data-source-item">Parsed Data: {n_periods} trading periods</div>
"""
        else:
            html += f"""                    <div class="data-source-item">{source_name.replace('_', ' ').title()}: Available</div>
"""

    html += """                </div>

                <h3>Analysis Components</h3>
                <ul class="insights-list">
                    <li>Statistical significance testing (bootstrap)</li>
                    <li>Out-of-sample validation</li>
                    <li>Risk-adjusted performance metrics</li>
                    <li>Decision calibration analysis</li>
                    <li>Baseline strategy comparisons</li>
                    <li>Rolling performance analysis</li>
                </ul>
            </div>
"""

    return html
